// <auto-generated>
// Generated by Viktor's art studio (temp/art/designs.py). 50 hand-designed
// vector crosshairs. Edit the Python source and regenerate rather than
// hand-editing coordinates.
// </auto-generated>
using System.Drawing;

namespace CrosshairOverlay
{
    internal static partial class ArtCrosshairs
    {
        private static ArtDef[] BuildDesigns() => new ArtDef[]
        {
            new ArtDef("Kunai", Color.FromArgb(188, 198, 214), Color.FromArgb(255, 84, 72), Color.FromArgb(255, 210, 120), Color.FromArgb(16, 18, 26), new Op[]
            {
                new Op(3, 0, 0f, new float[] { -0.1f, -1.05f, 0.1f, -1.05f, 0.05f, -0.62f, 0f, -0.34f, -0.05f, -0.62f }),
                new Op(0, 1, 0.05f, new float[] { 0f, -1.05f, 0f, -0.86f }),
                new Op(3, 0, 0f, new float[] { 1.05f, -0.1f, 1.05f, 0.1f, 0.62f, 0.05f, 0.34f, 0f, 0.62f, -0.05f }),
                new Op(0, 1, 0.05f, new float[] { 1.05f, 0f, 0.86f, 0f }),
                new Op(3, 0, 0f, new float[] { 0.1f, 1.05f, -0.1f, 1.05f, -0.05f, 0.62f, 0f, 0.34f, 0.05f, 0.62f }),
                new Op(0, 1, 0.05f, new float[] { 0f, 1.05f, 0f, 0.86f }),
                new Op(3, 0, 0f, new float[] { -1.05f, 0.1f, -1.05f, -0.1f, -0.62f, -0.05f, -0.34f, 0f, -0.62f, 0.05f }),
                new Op(0, 1, 0.05f, new float[] { -1.05f, 0f, -0.86f, 0f }),
                new Op(5, 1, 0f, new float[] { 0f, 0f, 0.075f }),
            }),
            new ArtDef("Lotus", Color.FromArgb(255, 148, 196), Color.FromArgb(84, 226, 206), Color.FromArgb(255, 244, 214), Color.FromArgb(38, 12, 30), new Op[]
            {
                new Op(3, 0, 0f, new float[] { 0f, -0.18f, 0.047f, -0.227f, 0.088f, -0.274f, 0.122f, -0.322f, 0.15f, -0.37f, 0.172f, -0.419f, 0.188f, -0.469f, 0.197f, -0.519f, 0.2f, -0.57f, 0.197f, -0.622f, 0.188f, -0.674f, 0.172f, -0.727f, 0.15f, -0.78f, 0.122f, -0.834f, 0.088f, -0.889f, 0.047f, -0.944f, 0f, -1f, 0f, -1f, -0.047f, -0.944f, -0.088f, -0.889f, -0.122f, -0.834f, -0.15f, -0.78f, -0.172f, -0.727f, -0.188f, -0.674f, -0.197f, -0.622f, -0.2f, -0.57f, -0.197f, -0.519f, -0.188f, -0.469f, -0.172f, -0.419f, -0.15f, -0.37f, -0.122f, -0.322f, -0.088f, -0.274f, -0.047f, -0.227f, 0f, -0.18f }),
                new Op(3, 0, 0f, new float[] { 0.18f, 0f, 0.227f, 0.047f, 0.274f, 0.087f, 0.322f, 0.122f, 0.37f, 0.15f, 0.419f, 0.172f, 0.469f, 0.187f, 0.519f, 0.197f, 0.57f, 0.2f, 0.622f, 0.197f, 0.674f, 0.187f, 0.727f, 0.172f, 0.78f, 0.15f, 0.834f, 0.122f, 0.889f, 0.087f, 0.944f, 0.047f, 1f, 0f, 1f, 0f, 0.944f, -0.047f, 0.889f, -0.088f, 0.834f, -0.122f, 0.78f, -0.15f, 0.727f, -0.172f, 0.674f, -0.188f, 0.622f, -0.197f, 0.57f, -0.2f, 0.519f, -0.197f, 0.469f, -0.188f, 0.419f, -0.172f, 0.37f, -0.15f, 0.322f, -0.122f, 0.274f, -0.088f, 0.227f, -0.047f, 0.18f, 0f }),
                new Op(3, 0, 0f, new float[] { 0f, 0.18f, -0.047f, 0.227f, -0.087f, 0.274f, -0.122f, 0.322f, -0.15f, 0.37f, -0.172f, 0.419f, -0.187f, 0.469f, -0.197f, 0.519f, -0.2f, 0.57f, -0.197f, 0.622f, -0.187f, 0.674f, -0.172f, 0.727f, -0.15f, 0.78f, -0.122f, 0.834f, -0.087f, 0.889f, -0.047f, 0.944f, 0f, 1f, 0f, 1f, 0.047f, 0.944f, 0.088f, 0.889f, 0.122f, 0.834f, 0.15f, 0.78f, 0.172f, 0.727f, 0.188f, 0.674f, 0.197f, 0.622f, 0.2f, 0.57f, 0.197f, 0.519f, 0.188f, 0.469f, 0.172f, 0.419f, 0.15f, 0.37f, 0.122f, 0.322f, 0.088f, 0.274f, 0.047f, 0.227f, 0f, 0.18f }),
                new Op(3, 0, 0f, new float[] { -0.18f, 0f, -0.227f, -0.047f, -0.274f, -0.087f, -0.322f, -0.122f, -0.37f, -0.15f, -0.419f, -0.172f, -0.469f, -0.187f, -0.519f, -0.197f, -0.57f, -0.2f, -0.622f, -0.197f, -0.674f, -0.187f, -0.727f, -0.172f, -0.78f, -0.15f, -0.834f, -0.122f, -0.889f, -0.087f, -0.944f, -0.047f, -1f, 0f, -1f, 0f, -0.944f, 0.047f, -0.889f, 0.088f, -0.834f, 0.122f, -0.78f, 0.15f, -0.727f, 0.172f, -0.674f, 0.188f, -0.622f, 0.197f, -0.57f, 0.2f, -0.519f, 0.197f, -0.469f, 0.188f, -0.419f, 0.172f, -0.37f, 0.15f, -0.322f, 0.122f, -0.274f, 0.088f, -0.227f, 0.047f, -0.18f, 0f }),
                new Op(5, 1, 0f, new float[] { 0f, 0f, 0.08f }),
            }),
            new ArtDef("Shuriken", Color.FromArgb(151, 164, 188), Color.FromArgb(122, 216, 255), Color.FromArgb(235, 240, 250), Color.FromArgb(12, 14, 22), new Op[]
            {
                new Op(3, 0, 0f, new float[] { 0.12f, -0.16f, 0.95f, -0.55f, 0.62f, -0.05f }),
                new Op(3, 0, 0f, new float[] { 0.16f, 0.12f, 0.55f, 0.95f, 0.05f, 0.62f }),
                new Op(3, 0, 0f, new float[] { -0.12f, 0.16f, -0.95f, 0.55f, -0.62f, 0.05f }),
                new Op(3, 0, 0f, new float[] { -0.16f, -0.12f, -0.55f, -0.95f, -0.05f, -0.62f }),
                new Op(4, 1, 0.07f, new float[] { 0f, 0f, 0.16f }),
            }),
            new ArtDef("Radar", Color.FromArgb(96, 255, 128), Color.FromArgb(40, 160, 80), Color.FromArgb(210, 255, 220), Color.FromArgb(6, 22, 12), new Op[]
            {
                new Op(4, 0, 0.07f, new float[] { 0f, 0f, 0.93f }),
                new Op(0, 0, 0.06f, new float[] { 0f, -1.02f, 0f, -0.84f }),
                new Op(0, 0, 0.06f, new float[] { 0.721f, -0.721f, 0.594f, -0.594f }),
                new Op(0, 0, 0.06f, new float[] { 1.02f, 0f, 0.84f, 0f }),
                new Op(0, 0, 0.06f, new float[] { 0.721f, 0.721f, 0.594f, 0.594f }),
                new Op(0, 0, 0.06f, new float[] { 0f, 1.02f, 0f, 0.84f }),
                new Op(0, 0, 0.06f, new float[] { -0.721f, 0.721f, -0.594f, 0.594f }),
                new Op(0, 0, 0.06f, new float[] { -1.02f, 0f, -0.84f, 0f }),
                new Op(0, 0, 0.06f, new float[] { -0.721f, -0.721f, -0.594f, -0.594f }),
                new Op(3, 1, 0f, new float[] { 0f, 0f, 0.78f, -0.34f, 0.84f, -0.1f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.07f }),
            }),
            new ArtDef("Atom", Color.FromArgb(186, 130, 255), Color.FromArgb(120, 220, 255), Color.FromArgb(255, 255, 255), Color.FromArgb(20, 10, 34), new Op[]
            {
                new Op(7, 0, 0.07f, new float[] { 0f, 0f, 1f, 0.4f, 0f }),
                new Op(7, 0, 0.07f, new float[] { 0f, 0f, 1f, 0.4f, 60f }),
                new Op(7, 1, 0.07f, new float[] { 0f, 0f, 1f, 0.4f, 120f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.09f }),
            }),
            new ArtDef("Compass", Color.FromArgb(235, 200, 120), Color.FromArgb(255, 96, 80), Color.FromArgb(250, 245, 230), Color.FromArgb(30, 22, 10), new Op[]
            {
                new Op(3, 1, 0f, new float[] { 0f, -1.12f, 0.15f, -0.5f, 0f, -0.34f, -0.15f, -0.5f }),
                new Op(3, 0, 0f, new float[] { 0f, 1.12f, 0.15f, 0.5f, 0f, 0.34f, -0.15f, 0.5f }),
                new Op(3, 0, 0f, new float[] { -1.12f, 0f, -0.5f, -0.15f, -0.34f, 0f, -0.5f, 0.15f }),
                new Op(3, 0, 0f, new float[] { 1.12f, 0f, 0.5f, -0.15f, 0.34f, 0f, 0.5f, 0.15f }),
                new Op(4, 2, 0.05f, new float[] { 0f, 0f, 0.55f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.05f }),
            }),
            new ArtDef("Aperture", Color.FromArgb(255, 184, 64), Color.FromArgb(130, 134, 150), Color.FromArgb(255, 240, 200), Color.FromArgb(18, 14, 8), new Op[]
            {
                new Op(0, 0, 0.1f, new float[] { 0.061f, -0.878f, 0.827f, -0.146f }),
                new Op(0, 0, 0.1f, new float[] { 0.791f, -0.386f, 0.54f, 0.643f }),
                new Op(0, 0, 0.1f, new float[] { 0.73f, 0.492f, -0.287f, 0.789f }),
                new Op(0, 0, 0.1f, new float[] { -0.061f, 0.878f, -0.827f, 0.146f }),
                new Op(0, 0, 0.1f, new float[] { -0.791f, 0.386f, -0.54f, -0.643f }),
                new Op(0, 0, 0.1f, new float[] { -0.73f, -0.492f, 0.287f, -0.789f }),
                new Op(4, 1, 0.06f, new float[] { 0f, 0f, 1.02f }),
            }),
            new ArtDef("Rune", Color.FromArgb(208, 226, 247), Color.FromArgb(110, 170, 220), Color.FromArgb(240, 250, 255), Color.FromArgb(14, 20, 30), new Op[]
            {
                new Op(1, 0, 0.1f, new float[] { -0.5f, -0.95f, 0f, -0.6f, 0.5f, -0.95f }),
                new Op(0, 1, 0.08f, new float[] { 0f, -0.6f, 0f, -0.3f }),
                new Op(1, 0, 0.1f, new float[] { 0.5f, 0.95f, 0f, 0.6f, -0.5f, 0.95f }),
                new Op(0, 1, 0.08f, new float[] { 0f, 0.6f, 0f, 0.3f }),
                new Op(0, 1, 0.08f, new float[] { -0.55f, 0f, -0.3f, 0f }),
                new Op(0, 1, 0.08f, new float[] { 0.3f, 0f, 0.55f, 0f }),
            }),
            new ArtDef("Hive", Color.FromArgb(255, 196, 64), Color.FromArgb(255, 140, 30), Color.FromArgb(255, 240, 200), Color.FromArgb(28, 18, 4), new Op[]
            {
                new Op(2, 0, 0.09f, new float[] { 0f, -1f, 0.866f, -0.5f, 0.866f, 0.5f, 0f, 1f, -0.866f, 0.5f, -0.866f, -0.5f }),
                new Op(2, 1, 0.07f, new float[] { 0f, -0.55f, 0.476f, -0.275f, 0.476f, 0.275f, 0f, 0.55f, -0.476f, 0.275f, -0.476f, -0.275f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.08f }),
            }),
            new ArtDef("Nova", Color.FromArgb(255, 240, 150), Color.FromArgb(255, 170, 60), Color.FromArgb(255, 255, 255), Color.FromArgb(30, 20, 6), new Op[]
            {
                new Op(2, 0, 0.08f, new float[] { 0f, -1.05f, 0.156f, -0.156f, 1.05f, 0f, 0.156f, 0.156f, 0f, 1.05f, -0.156f, 0.156f, -1.05f, 0f, -0.156f, -0.156f }),
                new Op(0, 1, 0.06f, new float[] { 0.55f, -0.55f, 0.75f, -0.75f }),
                new Op(0, 1, 0.06f, new float[] { 0.55f, 0.55f, 0.75f, 0.75f }),
                new Op(0, 1, 0.06f, new float[] { -0.55f, 0.55f, -0.75f, 0.75f }),
                new Op(0, 1, 0.06f, new float[] { -0.55f, -0.55f, -0.75f, -0.75f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.06f }),
            }),
            new ArtDef("Talon", Color.FromArgb(255, 120, 60), Color.FromArgb(200, 70, 40), Color.FromArgb(255, 220, 180), Color.FromArgb(28, 12, 6), new Op[]
            {
                new Op(6, 0, 0.11f, new float[] { 0.55f, -0.55f, 0.55f, 90f, 130f }),
                new Op(6, 0, 0.11f, new float[] { 0.201f, 0.751f, 0.55f, 210f, 130f }),
                new Op(6, 0, 0.11f, new float[] { -0.751f, -0.201f, 0.55f, 330f, 130f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.075f }),
            }),
            new ArtDef("Vortex", Color.FromArgb(110, 200, 255), Color.FromArgb(60, 120, 230), Color.FromArgb(220, 245, 255), Color.FromArgb(10, 16, 32), new Op[]
            {
                new Op(6, 0, 0.1f, new float[] { 0f, 0f, 0.95f, -90f, 95f }),
                new Op(6, 1, 0.08f, new float[] { 0f, 0f, 0.62f, -90f, 80f }),
                new Op(6, 0, 0.1f, new float[] { 0f, 0f, 0.95f, 30f, 95f }),
                new Op(6, 1, 0.08f, new float[] { 0f, 0f, 0.62f, 30f, 80f }),
                new Op(6, 0, 0.1f, new float[] { 0f, 0f, 0.95f, 150f, 95f }),
                new Op(6, 1, 0.08f, new float[] { 0f, 0f, 0.62f, 150f, 80f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.07f }),
            }),
            new ArtDef("Longbow", Color.FromArgb(180, 230, 140), Color.FromArgb(120, 90, 50), Color.FromArgb(255, 250, 230), Color.FromArgb(16, 22, 10), new Op[]
            {
                new Op(6, 1, 0.1f, new float[] { 0.25f, 0f, 1.05f, 115f, 130f }),
                new Op(0, 2, 0.045f, new float[] { -0.35f, -0.86f, -0.35f, 0.86f }),
                new Op(0, 0, 0.07f, new float[] { -0.35f, 0f, 0.95f, 0f }),
                new Op(3, 0, 0f, new float[] { 0.95f, 0f, 0.68f, -0.14f, 0.68f, 0.14f }),
                new Op(0, 0, 0.06f, new float[] { -0.35f, 0f, -0.18f, -0.1f }),
                new Op(0, 0, 0.06f, new float[] { -0.35f, 0f, -0.18f, 0.1f }),
            }),
            new ArtDef("Spire", Color.FromArgb(216, 196, 255), Color.FromArgb(140, 110, 220), Color.FromArgb(255, 250, 255), Color.FromArgb(20, 12, 36), new Op[]
            {
                new Op(1, 0, 0.09f, new float[] { -0.22f, -0.42f, -0.22f, -0.78f, 0f, -1.05f, 0.22f, -0.78f, 0.22f, -0.42f }),
                new Op(1, 0, 0.09f, new float[] { 0.42f, -0.22f, 0.78f, -0.22f, 1.05f, 0f, 0.78f, 0.22f, 0.42f, 0.22f }),
                new Op(1, 0, 0.09f, new float[] { 0.22f, 0.42f, 0.22f, 0.78f, 0f, 1.05f, -0.22f, 0.78f, -0.22f, 0.42f }),
                new Op(1, 0, 0.09f, new float[] { -0.42f, 0.22f, -0.78f, 0.22f, -1.05f, 0f, -0.78f, -0.22f, -0.42f, -0.22f }),
                new Op(5, 1, 0f, new float[] { 0f, 0f, 0.07f }),
            }),
            new ArtDef("Tribal", Color.FromArgb(240, 240, 240), Color.FromArgb(255, 90, 50), Color.FromArgb(255, 200, 160), Color.FromArgb(16, 10, 10), new Op[]
            {
                new Op(1, 0, 0.1f, new float[] { 0f, -1.05f, 0f, -0.42f }),
                new Op(3, 1, 0f, new float[] { 0f, -0.78f, 0.3f, -0.64f, 0f, -0.52f }),
                new Op(3, 1, 0f, new float[] { 0f, -1.05f, -0.24f, -0.94f, 0f, -0.86f }),
                new Op(1, 0, 0.1f, new float[] { 1.05f, 0f, 0.42f, 0f }),
                new Op(3, 1, 0f, new float[] { 0.78f, 0f, 0.64f, 0.3f, 0.52f, 0f }),
                new Op(3, 1, 0f, new float[] { 1.05f, 0f, 0.94f, -0.24f, 0.86f, 0f }),
                new Op(1, 0, 0.1f, new float[] { 0f, 1.05f, 0f, 0.42f }),
                new Op(3, 1, 0f, new float[] { 0f, 0.78f, -0.3f, 0.64f, 0f, 0.52f }),
                new Op(3, 1, 0f, new float[] { 0f, 1.05f, 0.24f, 0.94f, 0f, 0.86f }),
                new Op(1, 0, 0.1f, new float[] { -1.05f, 0f, -0.42f, 0f }),
                new Op(3, 1, 0f, new float[] { -0.78f, 0f, -0.64f, -0.3f, -0.52f, 0f }),
                new Op(3, 1, 0f, new float[] { -1.05f, 0f, -0.94f, 0.24f, -0.86f, 0f }),
                new Op(4, 0, 0.06f, new float[] { 0f, 0f, 0.16f }),
            }),
            new ArtDef("Frost", Color.FromArgb(200, 240, 255), Color.FromArgb(120, 190, 255), Color.FromArgb(255, 255, 255), Color.FromArgb(10, 22, 36), new Op[]
            {
                new Op(0, 0, 0.07f, new float[] { 0f, -0.25f, 0f, -1.05f }),
                new Op(0, 1, 0.06f, new float[] { 0f, -0.72f, 0.22f, -0.92f }),
                new Op(0, 1, 0.06f, new float[] { 0f, -0.72f, -0.22f, -0.92f }),
                new Op(0, 1, 0.05f, new float[] { 0f, -0.45f, 0.14f, -0.6f }),
                new Op(0, 1, 0.05f, new float[] { 0f, -0.45f, -0.14f, -0.6f }),
                new Op(0, 0, 0.07f, new float[] { 0.217f, -0.125f, 0.909f, -0.525f }),
                new Op(0, 1, 0.06f, new float[] { 0.624f, -0.36f, 0.907f, -0.269f }),
                new Op(0, 1, 0.06f, new float[] { 0.624f, -0.36f, 0.687f, -0.651f }),
                new Op(0, 1, 0.05f, new float[] { 0.39f, -0.225f, 0.59f, -0.179f }),
                new Op(0, 1, 0.05f, new float[] { 0.39f, -0.225f, 0.45f, -0.421f }),
                new Op(0, 0, 0.07f, new float[] { 0.217f, 0.125f, 0.909f, 0.525f }),
                new Op(0, 1, 0.06f, new float[] { 0.624f, 0.36f, 0.687f, 0.651f }),
                new Op(0, 1, 0.06f, new float[] { 0.624f, 0.36f, 0.907f, 0.269f }),
                new Op(0, 1, 0.05f, new float[] { 0.39f, 0.225f, 0.45f, 0.421f }),
                new Op(0, 1, 0.05f, new float[] { 0.39f, 0.225f, 0.59f, 0.179f }),
                new Op(0, 0, 0.07f, new float[] { 0f, 0.25f, 0f, 1.05f }),
                new Op(0, 1, 0.06f, new float[] { 0f, 0.72f, -0.22f, 0.92f }),
                new Op(0, 1, 0.06f, new float[] { 0f, 0.72f, 0.22f, 0.92f }),
                new Op(0, 1, 0.05f, new float[] { 0f, 0.45f, -0.14f, 0.6f }),
                new Op(0, 1, 0.05f, new float[] { 0f, 0.45f, 0.14f, 0.6f }),
                new Op(0, 0, 0.07f, new float[] { -0.217f, 0.125f, -0.909f, 0.525f }),
                new Op(0, 1, 0.06f, new float[] { -0.624f, 0.36f, -0.907f, 0.269f }),
                new Op(0, 1, 0.06f, new float[] { -0.624f, 0.36f, -0.687f, 0.651f }),
                new Op(0, 1, 0.05f, new float[] { -0.39f, 0.225f, -0.59f, 0.179f }),
                new Op(0, 1, 0.05f, new float[] { -0.39f, 0.225f, -0.45f, 0.421f }),
                new Op(0, 0, 0.07f, new float[] { -0.217f, -0.125f, -0.909f, -0.525f }),
                new Op(0, 1, 0.06f, new float[] { -0.624f, -0.36f, -0.687f, -0.651f }),
                new Op(0, 1, 0.06f, new float[] { -0.624f, -0.36f, -0.907f, -0.269f }),
                new Op(0, 1, 0.05f, new float[] { -0.39f, -0.225f, -0.45f, -0.421f }),
                new Op(0, 1, 0.05f, new float[] { -0.39f, -0.225f, -0.59f, -0.179f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.06f }),
            }),
            new ArtDef("Mil-Dot", Color.FromArgb(230, 235, 240), Color.FromArgb(255, 200, 60), Color.FromArgb(255, 255, 255), Color.FromArgb(12, 14, 18), new Op[]
            {
                new Op(0, 0, 0.055f, new float[] { 0f, -1.1f, 0f, -0.25f }),
                new Op(5, 1, 0f, new float[] { 0f, -0.55f, 0.05f }),
                new Op(5, 1, 0f, new float[] { 0f, -0.85f, 0.05f }),
                new Op(0, 0, 0.055f, new float[] { 1.1f, 0f, 0.25f, 0f }),
                new Op(5, 1, 0f, new float[] { 0.55f, 0f, 0.05f }),
                new Op(5, 1, 0f, new float[] { 0.85f, 0f, 0.05f }),
                new Op(0, 0, 0.055f, new float[] { 0f, 1.1f, 0f, 0.25f }),
                new Op(5, 1, 0f, new float[] { 0f, 0.55f, 0.05f }),
                new Op(5, 1, 0f, new float[] { 0f, 0.85f, 0.05f }),
                new Op(0, 0, 0.055f, new float[] { -1.1f, 0f, -0.25f, 0f }),
                new Op(5, 1, 0f, new float[] { -0.55f, 0f, 0.05f }),
                new Op(5, 1, 0f, new float[] { -0.85f, 0f, 0.05f }),
                new Op(4, 0, 0.04f, new float[] { 0f, 0f, 0.62f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.05f }),
            }),
            new ArtDef("Stadia", Color.FromArgb(140, 255, 180), Color.FromArgb(90, 200, 140), Color.FromArgb(240, 255, 245), Color.FromArgb(8, 24, 14), new Op[]
            {
                new Op(0, 0, 0.06f, new float[] { 0f, -1.05f, 0f, 1.05f }),
                new Op(0, 0, 0.06f, new float[] { -0.55f, -0.75f, 0.55f, -0.75f }),
                new Op(0, 1, 0.06f, new float[] { -0.4f, -0.4f, 0.4f, -0.4f }),
                new Op(0, 1, 0.055f, new float[] { -0.28f, 0.4f, 0.28f, 0.4f }),
                new Op(0, 1, 0.05f, new float[] { -0.18f, 0.75f, 0.18f, 0.75f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.06f }),
            }),
            new ArtDef("Chevrons", Color.FromArgb(255, 110, 130), Color.FromArgb(255, 170, 110), Color.FromArgb(255, 235, 200), Color.FromArgb(30, 8, 16), new Op[]
            {
                new Op(1, 0, 0.12f, new float[] { -0.62f, -0.95f, 0f, -0.55f, 0.62f, -0.95f }),
                new Op(1, 1, 0.1f, new float[] { -0.46f, -0.55f, 0f, -0.22f, 0.46f, -0.55f }),
                new Op(1, 2, 0.08f, new float[] { -0.3f, -0.16f, 0f, 0.08f, 0.3f, -0.16f }),
            }),
            new ArtDef("Corners", Color.FromArgb(90, 230, 220), Color.FromArgb(40, 160, 170), Color.FromArgb(230, 255, 252), Color.FromArgb(8, 22, 24), new Op[]
            {
                new Op(1, 0, 0.09f, new float[] { -0.85f, -0.45f, -0.85f, -0.85f, -0.45f, -0.85f }),
                new Op(1, 0, 0.09f, new float[] { 0.45f, -0.85f, 0.85f, -0.85f, 0.85f, -0.45f }),
                new Op(1, 0, 0.09f, new float[] { 0.85f, 0.45f, 0.85f, 0.85f, 0.45f, 0.85f }),
                new Op(1, 0, 0.09f, new float[] { -0.45f, 0.85f, -0.85f, 0.85f, -0.85f, 0.45f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.06f }),
            }),
            new ArtDef("Bullring", Color.FromArgb(255, 90, 90), Color.FromArgb(255, 200, 200), Color.FromArgb(255, 255, 255), Color.FromArgb(28, 8, 8), new Op[]
            {
                new Op(4, 0, 0.1f, new float[] { 0f, 0f, 0.85f }),
                new Op(4, 1, 0.07f, new float[] { 0f, 0f, 0.45f }),
                new Op(0, 0, 0.07f, new float[] { 0f, -1.12f, 0f, -0.95f }),
                new Op(0, 0, 0.07f, new float[] { 1.12f, 0f, 0.95f, 0f }),
                new Op(0, 0, 0.07f, new float[] { 0f, 1.12f, 0f, 0.95f }),
                new Op(0, 0, 0.07f, new float[] { -1.12f, 0f, -0.95f, 0f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.07f }),
            }),
            new ArtDef("Wasp", Color.FromArgb(255, 214, 40), Color.FromArgb(255, 150, 30), Color.FromArgb(255, 245, 200), Color.FromArgb(20, 16, 0), new Op[]
            {
                new Op(1, 0, 0.1f, new float[] { -0.95f, -0.55f, -0.35f, -0.25f, -0.95f, -0.05f }),
                new Op(1, 0, 0.1f, new float[] { 0.95f, -0.55f, 0.35f, -0.25f, 0.95f, -0.05f }),
                new Op(3, 1, 0f, new float[] { 0f, 0.3f, 0.16f, 0.58f, 0f, 1f, -0.16f, 0.58f }),
                new Op(0, 2, 0.05f, new float[] { -0.14f, 0.52f, 0.14f, 0.52f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.07f }),
            }),
            new ArtDef("Origami", Color.FromArgb(255, 255, 255), Color.FromArgb(170, 185, 210), Color.FromArgb(255, 120, 120), Color.FromArgb(24, 26, 34), new Op[]
            {
                new Op(3, 0, 0f, new float[] { 0f, -1f, 0.3f, -0.3f, 0f, -0.18f }),
                new Op(3, 1, 0f, new float[] { 0f, -1f, -0.3f, -0.3f, 0f, -0.18f }),
                new Op(3, 0, 0f, new float[] { 1f, 0f, 0.3f, 0.3f, 0.18f, 0f }),
                new Op(3, 1, 0f, new float[] { 1f, 0f, 0.3f, -0.3f, 0.18f, 0f }),
                new Op(3, 0, 0f, new float[] { 0f, 1f, -0.3f, 0.3f, 0f, 0.18f }),
                new Op(3, 1, 0f, new float[] { 0f, 1f, 0.3f, 0.3f, 0f, 0.18f }),
                new Op(3, 0, 0f, new float[] { -1f, 0f, -0.3f, -0.3f, -0.18f, 0f }),
                new Op(3, 1, 0f, new float[] { -1f, 0f, -0.3f, 0.3f, -0.18f, 0f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.06f }),
            }),
            new ArtDef("Circuit", Color.FromArgb(255, 178, 80), Color.FromArgb(90, 255, 170), Color.FromArgb(240, 255, 245), Color.FromArgb(8, 20, 16), new Op[]
            {
                new Op(1, 0, 0.07f, new float[] { 0f, -0.3f, 0f, -0.6f, 0.35f, -0.95f }),
                new Op(5, 1, 0f, new float[] { 0.35f, -0.95f, 0.09f }),
                new Op(4, 0, 0.05f, new float[] { 0f, -0.3f, 0.07f }),
                new Op(1, 0, 0.07f, new float[] { 0.3f, 0f, 0.6f, 0f, 0.95f, 0.35f }),
                new Op(5, 1, 0f, new float[] { 0.95f, 0.35f, 0.09f }),
                new Op(4, 0, 0.05f, new float[] { 0.3f, 0f, 0.07f }),
                new Op(1, 0, 0.07f, new float[] { 0f, 0.3f, 0f, 0.6f, -0.35f, 0.95f }),
                new Op(5, 1, 0f, new float[] { -0.35f, 0.95f, 0.09f }),
                new Op(4, 0, 0.05f, new float[] { 0f, 0.3f, 0.07f }),
                new Op(1, 0, 0.07f, new float[] { -0.3f, 0f, -0.6f, 0f, -0.95f, -0.35f }),
                new Op(5, 1, 0f, new float[] { -0.95f, -0.35f, 0.09f }),
                new Op(4, 0, 0.05f, new float[] { -0.3f, 0f, 0.07f }),
                new Op(4, 1, 0.05f, new float[] { 0f, 0f, 0.14f }),
            }),
            new ArtDef("Daisy", Color.FromArgb(255, 250, 255), Color.FromArgb(255, 210, 80), Color.FromArgb(255, 160, 200), Color.FromArgb(30, 22, 12), new Op[]
            {
                new Op(8, 0, 0f, new float[] { 0f, -0.74f, 0.115f, 0.27f, 90f }),
                new Op(8, 0, 0f, new float[] { 0.641f, -0.37f, 0.115f, 0.27f, 150f }),
                new Op(8, 0, 0f, new float[] { 0.641f, 0.37f, 0.115f, 0.27f, 210f }),
                new Op(8, 0, 0f, new float[] { 0f, 0.74f, 0.115f, 0.27f, 270f }),
                new Op(8, 0, 0f, new float[] { -0.641f, 0.37f, 0.115f, 0.27f, 330f }),
                new Op(8, 0, 0f, new float[] { -0.641f, -0.37f, 0.115f, 0.27f, 390f }),
                new Op(4, 1, 0.08f, new float[] { 0f, 0f, 0.26f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.06f }),
            }),
            new ArtDef("Taiji", Color.FromArgb(250, 250, 252), Color.FromArgb(130, 140, 160), Color.FromArgb(255, 80, 80), Color.FromArgb(18, 18, 24), new Op[]
            {
                new Op(6, 0, 0.11f, new float[] { 0f, 0f, 0.8f, -90f, 180f }),
                new Op(6, 1, 0.11f, new float[] { 0f, 0f, 0.8f, 90f, 180f }),
                new Op(5, 0, 0f, new float[] { 0f, 0.42f, 0.1f }),
                new Op(5, 1, 0f, new float[] { 0f, -0.42f, 0.1f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.06f }),
            }),
            new ArtDef("Hourglass", Color.FromArgb(255, 190, 90), Color.FromArgb(190, 120, 50), Color.FromArgb(255, 240, 210), Color.FromArgb(26, 16, 4), new Op[]
            {
                new Op(3, 0, 0f, new float[] { -0.55f, -0.95f, 0.55f, -0.95f, 0f, -0.18f }),
                new Op(3, 1, 0f, new float[] { -0.55f, 0.95f, 0.55f, 0.95f, 0f, 0.18f }),
                new Op(0, 2, 0.05f, new float[] { -0.75f, 0f, -0.3f, 0f }),
                new Op(0, 2, 0.05f, new float[] { 0.3f, 0f, 0.75f, 0f }),
            }),
            new ArtDef("Anchor", Color.FromArgb(120, 210, 230), Color.FromArgb(230, 200, 120), Color.FromArgb(250, 250, 240), Color.FromArgb(8, 20, 26), new Op[]
            {
                new Op(4, 1, 0.07f, new float[] { 0f, -0.78f, 0.2f }),
                new Op(0, 0, 0.08f, new float[] { 0f, -0.58f, 0f, 0.72f }),
                new Op(0, 0, 0.07f, new float[] { -0.42f, -0.3f, 0.42f, -0.3f }),
                new Op(6, 0, 0.08f, new float[] { 0f, 0.1f, 0.85f, 35f, 110f }),
                new Op(3, 1, 0f, new float[] { -0.85f, 0.3f, -0.62f, 0.62f, -0.95f, 0.62f }),
                new Op(3, 1, 0f, new float[] { 0.85f, 0.3f, 0.62f, 0.62f, 0.95f, 0.62f }),
            }),
            new ArtDef("Trident", Color.FromArgb(90, 220, 200), Color.FromArgb(255, 215, 130), Color.FromArgb(240, 255, 252), Color.FromArgb(6, 24, 22), new Op[]
            {
                new Op(0, 0, 0.08f, new float[] { 0f, 1.05f, 0f, -0.6f }),
                new Op(3, 0, 0f, new float[] { 0f, -1.05f, 0.12f, -0.72f, -0.12f, -0.72f }),
                new Op(1, 1, 0.07f, new float[] { -0.52f, -0.45f, -0.52f, -0.78f, -0.4f, -0.95f }),
                new Op(1, 1, 0.07f, new float[] { 0.52f, -0.45f, 0.52f, -0.78f, 0.4f, -0.95f }),
                new Op(0, 1, 0.07f, new float[] { -0.52f, -0.45f, 0.52f, -0.45f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.06f }),
            }),
            new ArtDef("Comet", Color.FromArgb(255, 255, 255), Color.FromArgb(120, 200, 255), Color.FromArgb(80, 120, 255), Color.FromArgb(10, 14, 30), new Op[]
            {
                new Op(1, 1, 0.09f, new float[] { 0.3f, -0.18f, 0.341f, -0.207f, 0.383f, -0.233f, 0.426f, -0.258f, 0.47f, -0.281f, 0.516f, -0.304f, 0.562f, -0.325f, 0.611f, -0.346f, 0.66f, -0.365f, 0.711f, -0.383f, 0.763f, -0.4f, 0.816f, -0.416f, 0.87f, -0.431f, 0.926f, -0.445f, 0.983f, -0.458f, 1.041f, -0.469f, 1.1f, -0.48f }),
                new Op(1, 1, 0.07f, new float[] { 0.22f, -0.34f, 0.256f, -0.375f, 0.292f, -0.408f, 0.33f, -0.441f, 0.369f, -0.472f, 0.409f, -0.503f, 0.45f, -0.533f, 0.492f, -0.562f, 0.535f, -0.59f, 0.579f, -0.617f, 0.625f, -0.643f, 0.671f, -0.668f, 0.719f, -0.693f, 0.767f, -0.716f, 0.817f, -0.738f, 0.868f, -0.76f, 0.92f, -0.78f }),
                new Op(1, 2, 0.06f, new float[] { 0.38f, -0.04f, 0.426f, -0.055f, 0.473f, -0.068f, 0.519f, -0.081f, 0.565f, -0.092f, 0.611f, -0.103f, 0.657f, -0.113f, 0.704f, -0.122f, 0.75f, -0.13f, 0.796f, -0.137f, 0.843f, -0.143f, 0.889f, -0.148f, 0.935f, -0.152f, 0.981f, -0.156f, 1.028f, -0.158f, 1.074f, -0.16f, 1.12f, -0.16f }),
                new Op(4, 0, 0.07f, new float[] { 0f, 0f, 0.18f }),
                new Op(5, 0, 0f, new float[] { 0f, 0f, 0.055f }),
            }),
            new ArtDef("Pixel", Color.FromArgb(120, 255, 120), Color.FromArgb(40, 170, 70), Color.FromArgb(220, 255, 220), Color.FromArgb(8, 24, 10), new Op[]
            {
                new Op(3, 0, 0f, new float[] { -0.11f, -0.77f, 0.11f, -0.77f, 0.11f, -0.55f, -0.11f, -0.55f }),
                new Op(3, 1, 0f, new float[] { -0.11f, -0.55f, 0.11f, -0.55f, 0.11f, -0.33f, -0.11f, -0.33f }),
                new Op(3, 0, 0f, new float[] { -0.11f, 0.55f, 0.11f, 0.55f, 0.11f, 0.77f, -0.11f, 0.77f }),
                new Op(3, 1, 0f, new float[] { -0.11f, 0.33f, 0.11f, 0.33f, 0.11f, 0.55f, -0.11f, 0.55f }),
                new Op(3, 0, 0f, new float[] { -0.77f, -0.11f, -0.55f, -0.11f, -0.55f, 0.11f, -0.77f, 0.11f }),
                new Op(3, 1, 0f, new float[] { -0.55f, -0.11f, -0.33f, -0.11f, -0.33f, 0.11f, -0.55f, 0.11f }),
                new Op(3, 0, 0f, new float[] { 0.55f, -0.11f, 0.77f, -0.11f, 0.77f, 0.11f, 0.55f, 0.11f }),
                new Op(3, 1, 0f, new float[] { 0.33f, -0.11f, 0.55f, -0.11f, 0.55f, 0.11f, 0.33f, 0.11f }),
                new Op(3, 2, 0f, new float[] { -0.11f, -0.11f, 0.11f, -0.11f, 0.11f, 0.11f, -0.11f, 0.11f }),
            }),
            new ArtDef("Sakura", Color.FromArgb(255, 170, 205), Color.FromArgb(255, 215, 230), Color.FromArgb(255, 255, 255), Color.FromArgb(40, 14, 30), new Op[]
            {
                new Op(8, 0, 0f, new float[] { 0f, -0.62f, 0.17f, 0.34f, 90f }),
                new Op(8, 0, 0f, new float[] { 0.59f, -0.192f, 0.17f, 0.34f, 162f }),
                new Op(8, 0, 0f, new float[] { 0.364f, 0.502f, 0.17f, 0.34f, 234f }),
                new Op(8, 0, 0f, new float[] { -0.364f, 0.502f, 0.17f, 0.34f, 306f }),
                new Op(8, 0, 0f, new float[] { -0.59f, -0.192f, 0.17f, 0.34f, 378f }),
                new Op(4, 1, 0.06f, new float[] { 0f, 0f, 0.2f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.05f }),
            }),
            new ArtDef("Dragonfly", Color.FromArgb(140, 230, 255), Color.FromArgb(80, 160, 230), Color.FromArgb(245, 250, 255), Color.FromArgb(10, 18, 34), new Op[]
            {
                new Op(8, 0, 0f, new float[] { 0.55f, -0.38f, 0.42f, 0.15f, -28f }),
                new Op(8, 0, 0f, new float[] { -0.55f, -0.38f, 0.42f, 0.15f, 28f }),
                new Op(8, 1, 0f, new float[] { 0.58f, 0.3f, 0.4f, 0.13f, 22f }),
                new Op(8, 1, 0f, new float[] { -0.58f, 0.3f, 0.4f, 0.13f, -22f }),
                new Op(0, 2, 0.08f, new float[] { 0f, -0.5f, 0f, 0.8f }),
                new Op(5, 2, 0f, new float[] { 0f, -0.6f, 0.1f }),
            }),
            new ArtDef("Cog", Color.FromArgb(200, 205, 215), Color.FromArgb(255, 170, 60), Color.FromArgb(240, 242, 248), Color.FromArgb(14, 14, 18), new Op[]
            {
                new Op(0, 0, 0.16f, new float[] { 0.306f, -0.739f, 0.39f, -0.942f }),
                new Op(0, 0, 0.16f, new float[] { 0.739f, -0.306f, 0.942f, -0.39f }),
                new Op(0, 0, 0.16f, new float[] { 0.739f, 0.306f, 0.942f, 0.39f }),
                new Op(0, 0, 0.16f, new float[] { 0.306f, 0.739f, 0.39f, 0.942f }),
                new Op(0, 0, 0.16f, new float[] { -0.306f, 0.739f, -0.39f, 0.942f }),
                new Op(0, 0, 0.16f, new float[] { -0.739f, 0.306f, -0.942f, 0.39f }),
                new Op(0, 0, 0.16f, new float[] { -0.739f, -0.306f, -0.942f, -0.39f }),
                new Op(0, 0, 0.16f, new float[] { -0.306f, -0.739f, -0.39f, -0.942f }),
                new Op(4, 0, 0.1f, new float[] { 0f, 0f, 0.8f }),
                new Op(4, 1, 0.06f, new float[] { 0f, 0f, 0.38f }),
                new Op(5, 1, 0f, new float[] { 0f, 0f, 0.07f }),
            }),
            new ArtDef("Crystal", Color.FromArgb(130, 240, 230), Color.FromArgb(60, 150, 200), Color.FromArgb(235, 255, 252), Color.FromArgb(8, 22, 28), new Op[]
            {
                new Op(3, 0, 0f, new float[] { 0f, -1.05f, 0.5f, -0.45f, 0.3f, 0.35f, 0f, 0.7f }),
                new Op(3, 1, 0f, new float[] { 0f, -1.05f, -0.5f, -0.45f, -0.3f, 0.35f, 0f, 0.7f }),
                new Op(0, 2, 0.045f, new float[] { 0f, -1.05f, 0f, 0.7f }),
                new Op(0, 2, 0.045f, new float[] { -0.5f, -0.45f, 0.5f, -0.45f }),
            }),
            new ArtDef("Arrowstorm", Color.FromArgb(255, 140, 90), Color.FromArgb(255, 90, 120), Color.FromArgb(255, 230, 200), Color.FromArgb(26, 10, 8), new Op[]
            {
                new Op(3, 0, 0f, new float[] { 0f, -0.3f, 0.26f, -0.72f, 0f, -0.58f, -0.26f, -0.72f }),
                new Op(3, 0, 0f, new float[] { 0.3f, 0f, 0.72f, 0.26f, 0.58f, 0f, 0.72f, -0.26f }),
                new Op(3, 0, 0f, new float[] { 0f, 0.3f, -0.26f, 0.72f, 0f, 0.58f, 0.26f, 0.72f }),
                new Op(3, 0, 0f, new float[] { -0.3f, 0f, -0.72f, -0.26f, -0.58f, 0f, -0.72f, 0.26f }),
                new Op(0, 1, 0.06f, new float[] { 0f, -0.78f, 0f, -1.02f }),
                new Op(0, 1, 0.06f, new float[] { 0.78f, 0f, 1.02f, 0f }),
                new Op(0, 1, 0.06f, new float[] { 0f, 0.78f, 0f, 1.02f }),
                new Op(0, 1, 0.06f, new float[] { -0.78f, 0f, -1.02f, 0f }),
            }),
            new ArtDef("Saber", Color.FromArgb(170, 240, 255), Color.FromArgb(90, 160, 255), Color.FromArgb(255, 255, 255), Color.FromArgb(12, 18, 36), new Op[]
            {
                new Op(0, 0, 0.09f, new float[] { 0f, -1.05f, 0f, -0.2f }),
                new Op(0, 0, 0.09f, new float[] { 0f, 0.2f, 0f, 0.55f }),
                new Op(0, 1, 0.07f, new float[] { -0.3f, 0.55f, 0.3f, 0.55f }),
                new Op(6, 1, 0.07f, new float[] { 0f, 0f, 0.45f, 150f, 240f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.05f }),
            }),
            new ArtDef("Widow", Color.FromArgb(220, 220, 228), Color.FromArgb(255, 60, 60), Color.FromArgb(250, 250, 255), Color.FromArgb(14, 12, 16), new Op[]
            {
                new Op(1, 0, 0.07f, new float[] { 0.18f, -0.3f, 0.45f, -0.7f, 0.4f, -1.05f }),
                new Op(1, 0, 0.07f, new float[] { 0.3f, 0.18f, 0.7f, 0.45f, 1.05f, 0.4f }),
                new Op(1, 0, 0.07f, new float[] { -0.18f, 0.3f, -0.45f, 0.7f, -0.4f, 1.05f }),
                new Op(1, 0, 0.07f, new float[] { -0.3f, -0.18f, -0.7f, -0.45f, -1.05f, -0.4f }),
                new Op(1, 0, 0.07f, new float[] { -0.18f, -0.3f, -0.45f, -0.7f, -0.4f, -1.05f }),
                new Op(1, 0, 0.07f, new float[] { -0.3f, 0.18f, -0.7f, 0.45f, -1.05f, 0.4f }),
                new Op(1, 0, 0.07f, new float[] { 0.18f, 0.3f, 0.45f, 0.7f, 0.4f, 1.05f }),
                new Op(1, 0, 0.07f, new float[] { 0.3f, -0.18f, 0.7f, -0.45f, 1.05f, -0.4f }),
                new Op(4, 0, 0.07f, new float[] { 0f, 0f, 0.3f }),
                new Op(3, 1, 0f, new float[] { 0f, -0.1f, 0.08f, 0.04f, 0f, 0.18f, -0.08f, 0.04f }),
            }),
            new ArtDef("Torii", Color.FromArgb(255, 90, 70), Color.FromArgb(200, 60, 50), Color.FromArgb(255, 230, 200), Color.FromArgb(30, 10, 8), new Op[]
            {
                new Op(1, 0, 0.1f, new float[] { -1.05f, -0.72f, -0.919f, -0.747f, -0.788f, -0.77f, -0.656f, -0.79f, -0.525f, -0.806f, -0.394f, -0.819f, -0.262f, -0.828f, -0.131f, -0.833f, 0f, -0.835f, 0.131f, -0.833f, 0.262f, -0.828f, 0.394f, -0.819f, 0.525f, -0.806f, 0.656f, -0.79f, 0.788f, -0.77f, 0.919f, -0.747f, 1.05f, -0.72f }),
                new Op(0, 1, 0.08f, new float[] { -0.78f, -0.45f, 0.78f, -0.45f }),
                new Op(0, 0, 0.09f, new float[] { -0.62f, -0.45f, -0.62f, 0.85f }),
                new Op(0, 0, 0.09f, new float[] { 0.62f, -0.45f, 0.62f, 0.85f }),
                new Op(0, 1, 0.06f, new float[] { 0f, -0.72f, 0f, -0.45f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.06f }),
            }),
            new ArtDef("Beacon", Color.FromArgb(255, 220, 90), Color.FromArgb(130, 200, 255), Color.FromArgb(255, 250, 230), Color.FromArgb(24, 18, 6), new Op[]
            {
                new Op(5, 0, 0f, new float[] { 0f, -0.85f, 0.13f }),
                new Op(6, 1, 0.06f, new float[] { 0f, 0f, 0.85f, -65f, 50f }),
                new Op(5, 0, 0f, new float[] { 0.736f, 0.425f, 0.13f }),
                new Op(6, 1, 0.06f, new float[] { 0f, 0f, 0.85f, 55f, 50f }),
                new Op(5, 0, 0f, new float[] { -0.736f, 0.425f, 0.13f }),
                new Op(6, 1, 0.06f, new float[] { 0f, 0f, 0.85f, 175f, 50f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.06f }),
            }),
            new ArtDef("Duplex", Color.FromArgb(235, 238, 245), Color.FromArgb(170, 176, 188), Color.FromArgb(255, 110, 60), Color.FromArgb(16, 17, 22), new Op[]
            {
                new Op(0, 0, 0.15f, new float[] { 0f, -1.1f, 0f, -0.55f }),
                new Op(0, 1, 0.05f, new float[] { 0f, -0.55f, 0f, -0.16f }),
                new Op(0, 0, 0.15f, new float[] { 1.1f, 0f, 0.55f, 0f }),
                new Op(0, 1, 0.05f, new float[] { 0.55f, 0f, 0.16f, 0f }),
                new Op(0, 0, 0.15f, new float[] { 0f, 1.1f, 0f, 0.55f }),
                new Op(0, 1, 0.05f, new float[] { 0f, 0.55f, 0f, 0.16f }),
                new Op(0, 0, 0.15f, new float[] { -1.1f, 0f, -0.55f, 0f }),
                new Op(0, 1, 0.05f, new float[] { -0.55f, 0f, -0.16f, 0f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.05f }),
            }),
            new ArtDef("Pulse", Color.FromArgb(110, 255, 170), Color.FromArgb(255, 110, 130), Color.FromArgb(240, 255, 246), Color.FromArgb(8, 24, 14), new Op[]
            {
                new Op(1, 0, 0.07f, new float[] { 0.18f, 0f, 0.34f, 0f, 0.45f, -0.22f, 0.58f, 0.22f, 0.68f, 0f, 1.05f, 0f }),
                new Op(1, 0, 0.07f, new float[] { -0.18f, 0f, -0.34f, 0f, -0.45f, -0.22f, -0.58f, 0.22f, -0.68f, 0f, -1.05f, 0f }),
                new Op(5, 1, 0f, new float[] { 0f, 0f, 0.07f }),
            }),
            new ArtDef("Falconer", Color.FromArgb(255, 200, 120), Color.FromArgb(190, 120, 70), Color.FromArgb(255, 245, 225), Color.FromArgb(26, 16, 6), new Op[]
            {
                new Op(1, 0, 0.1f, new float[] { -0.95f, -0.3f, -0.863f, -0.402f, -0.77f, -0.493f, -0.67f, -0.571f, -0.566f, -0.637f, -0.458f, -0.691f, -0.346f, -0.733f, -0.232f, -0.763f, -0.117f, -0.781f, 0f, -0.787f, 0.117f, -0.781f, 0.232f, -0.763f, 0.346f, -0.733f, 0.458f, -0.691f, 0.566f, -0.637f, 0.67f, -0.571f, 0.77f, -0.493f, 0.863f, -0.402f, 0.95f, -0.3f }),
                new Op(1, 1, 0.08f, new float[] { -0.62f, -0.25f, -0.561f, -0.315f, -0.499f, -0.371f, -0.434f, -0.421f, -0.366f, -0.463f, -0.295f, -0.497f, -0.223f, -0.523f, -0.149f, -0.542f, -0.075f, -0.554f, 0f, -0.557f, 0.075f, -0.554f, 0.149f, -0.542f, 0.223f, -0.523f, 0.295f, -0.497f, 0.366f, -0.463f, 0.434f, -0.421f, 0.499f, -0.371f, 0.561f, -0.315f, 0.62f, -0.25f }),
                new Op(1, 0, 0.1f, new float[] { -0.95f, 0.3f, -0.863f, 0.402f, -0.77f, 0.493f, -0.67f, 0.571f, -0.566f, 0.637f, -0.458f, 0.691f, -0.346f, 0.733f, -0.232f, 0.763f, -0.117f, 0.781f, 0f, 0.787f, 0.117f, 0.781f, 0.232f, 0.763f, 0.346f, 0.733f, 0.458f, 0.691f, 0.566f, 0.637f, 0.67f, 0.571f, 0.77f, 0.493f, 0.863f, 0.402f, 0.95f, 0.3f }),
                new Op(1, 1, 0.08f, new float[] { -0.62f, 0.25f, -0.561f, 0.315f, -0.499f, 0.371f, -0.434f, 0.421f, -0.366f, 0.463f, -0.295f, 0.497f, -0.223f, 0.523f, -0.149f, 0.542f, -0.075f, 0.554f, 0f, 0.557f, 0.075f, 0.554f, 0.149f, 0.542f, 0.223f, 0.523f, 0.295f, 0.497f, 0.366f, 0.463f, 0.434f, 0.421f, 0.499f, 0.371f, 0.561f, 0.315f, 0.62f, 0.25f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.07f }),
            }),
            new ArtDef("Labyrinth", Color.FromArgb(230, 180, 110), Color.FromArgb(160, 120, 80), Color.FromArgb(250, 235, 210), Color.FromArgb(22, 14, 6), new Op[]
            {
                new Op(1, 0, 0.08f, new float[] { -0.95f, -0.35f, -0.95f, -0.95f, -0.35f, -0.95f, -0.35f, -0.62f, -0.62f, -0.62f }),
                new Op(1, 0, 0.08f, new float[] { 0.35f, -0.95f, 0.95f, -0.95f, 0.95f, -0.35f, 0.62f, -0.35f, 0.62f, -0.62f }),
                new Op(1, 0, 0.08f, new float[] { 0.95f, 0.35f, 0.95f, 0.95f, 0.35f, 0.95f, 0.35f, 0.62f, 0.62f, 0.62f }),
                new Op(1, 0, 0.08f, new float[] { -0.35f, 0.95f, -0.95f, 0.95f, -0.95f, 0.35f, -0.62f, 0.35f, -0.62f, 0.62f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.06f }),
            }),
            new ArtDef("Ouroboros", Color.FromArgb(150, 230, 140), Color.FromArgb(80, 170, 90), Color.FromArgb(240, 255, 240), Color.FromArgb(10, 22, 10), new Op[]
            {
                new Op(6, 0, 0.1f, new float[] { 0f, 0f, 0.88f, -80f, 60f }),
                new Op(6, 1, 0.1f, new float[] { 0f, 0f, 0.88f, 10f, 60f }),
                new Op(6, 0, 0.1f, new float[] { 0f, 0f, 0.88f, 100f, 60f }),
                new Op(6, 1, 0.1f, new float[] { 0f, 0f, 0.88f, 190f, 60f }),
                new Op(3, 2, 0f, new float[] { 0.38f, -1.06f, 0.06f, -0.86f, 0.46f, -0.66f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.06f }),
            }),
            new ArtDef("Stiletto", Color.FromArgb(245, 245, 250), Color.FromArgb(255, 70, 90), Color.FromArgb(255, 255, 255), Color.FromArgb(16, 16, 22), new Op[]
            {
                new Op(0, 0, 0.05f, new float[] { 0f, -1.1f, 0f, -0.14f }),
                new Op(3, 1, 0f, new float[] { 0f, -0.14f, 0.05f, -0.3f, -0.05f, -0.3f }),
                new Op(0, 0, 0.05f, new float[] { -0.3f, -0.72f, 0.3f, -0.72f }),
                new Op(0, 0, 0.045f, new float[] { -0.16f, 0.35f, 0.16f, 0.35f }),
                new Op(0, 0, 0.05f, new float[] { 0f, 0.35f, 0f, 0.75f }),
            }),
            new ArtDef("Quasar", Color.FromArgb(255, 120, 220), Color.FromArgb(140, 90, 255), Color.FromArgb(255, 235, 255), Color.FromArgb(26, 8, 32), new Op[]
            {
                new Op(3, 0, 0f, new float[] { 0.3f, -0.3f, 1f, -0.62f, 0.62f, -1f }),
                new Op(3, 0, 0f, new float[] { 0.3f, 0.3f, 0.62f, 1f, 1f, 0.62f }),
                new Op(3, 0, 0f, new float[] { -0.3f, 0.3f, -1f, 0.62f, -0.62f, 1f }),
                new Op(3, 0, 0f, new float[] { -0.3f, -0.3f, -0.62f, -1f, -1f, -0.62f }),
                new Op(4, 1, 0.05f, new float[] { 0f, 0f, 0.5f }),
                new Op(5, 2, 0f, new float[] { 0f, 0f, 0.06f }),
            }),
            new ArtDef("Sundial", Color.FromArgb(255, 215, 140), Color.FromArgb(180, 150, 110), Color.FromArgb(90, 70, 50), Color.FromArgb(24, 18, 8), new Op[]
            {
                new Op(0, 1, 0.05f, new float[] { 0f, -0.88f, 0f, -1.02f }),
                new Op(0, 1, 0.05f, new float[] { 0.44f, -0.762f, 0.51f, -0.883f }),
                new Op(0, 1, 0.05f, new float[] { 0.762f, -0.44f, 0.883f, -0.51f }),
                new Op(0, 1, 0.05f, new float[] { 0.88f, 0f, 1.02f, 0f }),
                new Op(0, 1, 0.05f, new float[] { 0.762f, 0.44f, 0.883f, 0.51f }),
                new Op(0, 1, 0.05f, new float[] { 0.44f, 0.762f, 0.51f, 0.883f }),
                new Op(0, 1, 0.05f, new float[] { 0f, 0.88f, 0f, 1.02f }),
                new Op(0, 1, 0.05f, new float[] { -0.44f, 0.762f, -0.51f, 0.883f }),
                new Op(0, 1, 0.05f, new float[] { -0.762f, 0.44f, -0.883f, 0.51f }),
                new Op(0, 1, 0.05f, new float[] { -0.88f, 0f, -1.02f, 0f }),
                new Op(0, 1, 0.05f, new float[] { -0.762f, -0.44f, -0.883f, -0.51f }),
                new Op(0, 1, 0.05f, new float[] { -0.44f, -0.762f, -0.51f, -0.883f }),
                new Op(4, 0, 0.07f, new float[] { 0f, 0f, 0.95f }),
                new Op(3, 2, 0f, new float[] { 0f, 0f, 0.38f, 0.55f, 0.1f, 0.62f }),
                new Op(5, 0, 0f, new float[] { 0f, 0f, 0.07f }),
            }),
            new ArtDef("Phoenix", Color.FromArgb(255, 150, 50), Color.FromArgb(255, 80, 60), Color.FromArgb(255, 230, 160), Color.FromArgb(32, 10, 4), new Op[]
            {
                new Op(1, 0, 0.1f, new float[] { -0.2f, 0.8f, -0.303f, 0.753f, -0.396f, 0.696f, -0.479f, 0.629f, -0.551f, 0.554f, -0.612f, 0.472f, -0.663f, 0.383f, -0.703f, 0.289f, -0.732f, 0.19f, -0.75f, 0.088f, -0.757f, -0.018f, -0.753f, -0.125f, -0.737f, -0.233f, -0.71f, -0.342f, -0.671f, -0.449f, -0.621f, -0.554f, -0.559f, -0.657f, -0.486f, -0.756f, -0.4f, -0.85f }),
                new Op(1, 0, 0.1f, new float[] { 0.2f, 0.8f, 0.303f, 0.753f, 0.396f, 0.696f, 0.479f, 0.629f, 0.551f, 0.554f, 0.612f, 0.472f, 0.663f, 0.383f, 0.703f, 0.289f, 0.732f, 0.19f, 0.75f, 0.088f, 0.757f, -0.018f, 0.753f, -0.125f, 0.737f, -0.233f, 0.71f, -0.342f, 0.671f, -0.449f, 0.621f, -0.554f, 0.559f, -0.657f, 0.486f, -0.756f, 0.4f, -0.85f }),
                new Op(1, 1, 0.08f, new float[] { -0.12f, 0.55f, -0.188f, 0.518f, -0.249f, 0.481f, -0.303f, 0.437f, -0.35f, 0.389f, -0.391f, 0.336f, -0.424f, 0.279f, -0.45f, 0.219f, -0.469f, 0.156f, -0.481f, 0.09f, -0.487f, 0.022f, -0.485f, -0.046f, -0.476f, -0.116f, -0.461f, -0.186f, -0.438f, -0.255f, -0.409f, -0.324f, -0.373f, -0.391f, -0.33f, -0.457f, -0.28f, -0.52f }),
                new Op(1, 1, 0.08f, new float[] { 0.12f, 0.55f, 0.188f, 0.518f, 0.249f, 0.481f, 0.303f, 0.437f, 0.35f, 0.389f, 0.391f, 0.336f, 0.424f, 0.279f, 0.45f, 0.219f, 0.469f, 0.156f, 0.481f, 0.09f, 0.487f, 0.022f, 0.485f, -0.046f, 0.476f, -0.116f, 0.461f, -0.186f, 0.438f, -0.255f, 0.409f, -0.324f, 0.373f, -0.391f, 0.33f, -0.457f, 0.28f, -0.52f }),
                new Op(5, 2, 0f, new float[] { 0f, -0.02f, 0.09f }),
                new Op(1, 2, 0.06f, new float[] { -0.3f, 0.72f, -0.263f, 0.743f, -0.225f, 0.764f, -0.187f, 0.781f, -0.15f, 0.795f, -0.112f, 0.806f, -0.075f, 0.814f, -0.038f, 0.818f, 0f, 0.82f, 0.038f, 0.818f, 0.075f, 0.814f, 0.112f, 0.806f, 0.15f, 0.795f, 0.187f, 0.781f, 0.225f, 0.764f, 0.263f, 0.743f, 0.3f, 0.72f }),
            }),
            new ArtDef("Eclipse", Color.FromArgb(255, 230, 140), Color.FromArgb(255, 255, 255), Color.FromArgb(90, 100, 130), Color.FromArgb(20, 16, 30), new Op[]
            {
                new Op(6, 0, 0.12f, new float[] { 0f, 0f, 0.72f, 110f, 220f }),
                new Op(6, 1, 0.05f, new float[] { 0f, 0f, 0.92f, 130f, 160f }),
                new Op(4, 2, 0.06f, new float[] { 0f, 0f, 0.4f }),
                new Op(5, 1, 0f, new float[] { 0.62f, -0.62f, 0.06f }),
                new Op(5, 1, 0f, new float[] { 0f, 0f, 0.05f }),
            }),
        };
    }
}
